// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvvohycbniyuhcgcyszi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dm9oeWNibml5dWhjZ2N5c3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjU2MTMsImV4cCI6MjA2NzgwMTYxM30.YsZN-cpR7oSJVMluoihE4_A22msLFDLgi9jNfyr_ihc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});